services:
  - type: web
    name: cloud-canvas
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 4 --forwarded-allow-ips='*' --access-logfile - 'app:create_app()'
    healthCheckPath: /api/health
